### ISSUE TITLE
ansible-vault command not found

### ISSUE THREAD

**Issue by johnreytanquinco** [hashicorp/terraform-provider-external#144]
### Terraform CLI and Provider Versions

$ terraform --version
Terraform v0.14.3
Your version of Terraform is out of date! The latest version
is 1.2.5. You can update by downloading from https://www.terraform.io/downloads.html
$ terraform init
Initializing the backend...
Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Finding latest version of hashicorp/azurerm...
- Finding latest version of hashicorp/external...
- Installing hashicorp/azurerm v3.14.0...
- Installed hashicorp/azurerm v3.14.0 (self-signed, key ID XXXXXXXXX)
- Installing hashicorp/external v2.2.2...
- Installed hashicorp/external v2.2.2 (self-signed, key ID XXXXXXXX)

### Terraform Configuration

```terraform
# variables.tf

data "external" "ansible" {
  program  = [
    "./vault.sh",
    "group_vars/dev/vars.yml"
  ]
}

# vault.sh
#!/usr/bin/env bash

set -e

vault_file_path=$1
if [ -z $vault_file_path ]; then
    echo You need to provide vault file path as the first argument. None received.
    exit 2
fi

ansible-vault decrypt --output - $vault_file_path --vault-password-file pass
```

### Expected Behavior

data source should be able to run the script.

### Actual Behavior

$ terraform plan -out=$PLAN -input=false
Acquiring state lock. This may take a few moments...
Error: External Program Execution Failed
  on variables.tf line 26, in data "external" "ansible":
  26:   program  = [
  27:     "./vault.sh",
  28:     "group_vars/dev/vars.yml"
  29:   ]
The data source received an unexpected error while attempting to execute the
program.
Program: ./vault.sh
Error Message: ./vault.sh: line 11: ansible-vault: command not found
State: exit status 127

### Steps to Reproduce

1. `terraform plan -out=$PLAN -input=false`
Im running it from gitlab ci.

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @johnreytanquinco 👋 Thank you for raising this issue and sorry you ran into trouble here. Were you able to resolve the issue?

This type of error is unfortunately difficult for the provider maintainers to provide too much assistance with since it will be environment or operating system specific to where Terraform is being ran. This error:

```text
Error Message: ./vault.sh: line 11: ansible-vault: command not found
```

Implies that either the `ansible-vault` tool is not installed properly where Terraform is running or the tool is installed in a directory that is not "known" to the operating system. For example, many operating systems use the `PATH` environment variable when determining where to look for potential executable programs.

**Comment by johnreytanquinco** [comment]
Yes, that looks to be issue. Thanks for pointing out.
