### ISSUE TITLE
external provider does not log what its trying to do

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-external#22]
Terraform-provider-external v1.0.0
Terraform all versions

I'm running a complicated external command. It's not working. What would be really useful in debugging why is that if I set TF_LOG to trace, the provider logs what its attempting to do, so I can reconcile the output, but it doesnt log anything. 

This makes debugging so much more difficult than it needs to be. Could we have some debug please?!

**Comment by gtmtech** [comment]
By "what its attempting to do" - I mean the command its trying to run.

**Comment by jonas-chevalier-da** [comment]
It would be nice if it could behave a bit more like the local-exec provisioner and print the stderr as well

**Comment by paultyng** [comment]
#36 added trace logging of the output of the command, but still no tracing of the command itself.

**Comment by techdragon** [comment]
The fact this has been open for 3 years is ... I'll be honest, both damning and deeply disheartening. 

[I can't give you a PR because you don't have staff time/resources to review community contributions](https://github.com/hashicorp/terraform/commit/6562466c32a8750d7a71a6cc6232e6b5a28fe13a), and you leave _basic functionality_ that has _**serious security implications**_ broken for years (I say broken because #36 should never have passed review without also fixing this, I know I would have kicked it back)... when lets be fair... this is at absolute worst 1 days work for a junior developer, heck its probably less than 1 days work even if the junior developer never used GoLang before that's how trivial this is.

**Comment by bflad** [comment]
Hi @techdragon 👋  This project is maintained by a different set of maintainers and willing to review contributions in this area. We just haven't seen much interest in this issue (e.g. 👍  count) or any submissions so it hasn't been prioritized against other work.

If someone is interested in working on this, there's two options:

Using `log.Printf()`:

```go
log.Printf("Program: %s", cmd.String())
```

Using the new [terraform-plugin-log `tflog` package](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-log/tflog)

This is a little bit more of an invasive change to future proof things, but has the benefit of providing much more information in the logs. This requires switching the data source Read functionality to be context aware, then passing that context through `tflog` calls. If this is done, the JSON result logging should also be updated.

---

We are planning to cut a release of this provider shortly for other reasons, so now may be a great time to get something in.
