### ISSUE TITLE
data external does not allow me to run any powershell command in linux vm

### ISSUE THREAD

**Issue by Kailash-P** [hashicorp/terraform-provider-external#25]
Hi there,

Hi i am trying to execute external data provider in terraform for powershell.exe using azure provider and i am getting the following error

can't find external program "Powershell.exe"

i have my powershell.exe and terraform setup installed in my linux vm

### Terraform Version
0.11.0

**Comment by mildwonkey** [comment]
Hi @Kailash-P ,
The error you mentioned is returned if the provider can't find the given program via the PATH environment variable, or if that program is not executable. 

Can you check if "Powershell.exe" is in your linux vm's PATH and (the more likely issue, since it sounds like you're trying to run powershell from the linux vm) able to be executed from that same vm?

**Comment by kabal2010** [comment]
PowerShell.exe does not exist in Linux. You can install PowerShell and use **pwsh** to execute the script.

**Comment by bflad** [comment]
Closing as the above two responses should cover this issue. Thank you, @mildwonkey and @kabal2010. 😄
