### ISSUE TITLE
Deployed documentation may not be up-to-date

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform-provider-external#30]
Documentation for the `working_dir` parameter appears to be missing from the documentation site, despite being committed [just over a year ago](https://github.com/terraform-providers/terraform-provider-external/commit/4f8d4ef43cf27823b81d5ca6c7c33e5fe0eb0a4c):

---

From https://www.terraform.io/docs/providers/external/data_source.html#argument-reference:

![image](https://user-images.githubusercontent.com/900469/53931911-4c1d6d80-40eb-11e9-94e1-2afab2fbb43b.png)

---

From https://github.com/terraform-providers/terraform-provider-external/blob/master/website/docs/data_source.html.md:

![image](https://user-images.githubusercontent.com/900469/53931943-68b9a580-40eb-11e9-8ebe-1f827bd3b856.png)

**Comment by bflad** [comment]
Thanks for raising this, @tdmalone 👍  Since this issue was raised awhile ago, provider documentation is now hosted in the [Terraform Registry](https://registry.terraform.io/) instead of the [Terraform documentation](https://terraform.io/docs/). The [latest version of the provider documentation](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) contains the `working_dir` attribute as expected.
