### ISSUE TITLE
Adding depends_on to an external data source causes "apply" to prompt for changes each time

### ISSUE THREAD

**Issue by elias314** [hashicorp/terraform-provider-external#43]
I've been using an external data source to do some work after resources are deployed, so I need the external data source to run at the end of the resource creation.  When I add `depends_on` to the data source, it correctly runs after the dependent resource, but subsequent runs of `apply` cause Terraform to prompt for confirmation.  If I comment out the `depends_on`, the data source still runs, but Terraform doesn't throw up the confirmation prompt.

Note that this example uses an `aws_ecs_cluster` as the dependent resource because that's how I discovered this issue, but it appears to affect other resources as well.

### Terraform Version

```
Terraform v0.12.26
+ provider.aws v2.64.0
+ provider.external v1.2.0
```

### Affected Resource(s)

* External data sources

### Terraform Configuration Files
```hcl
terraform {
  backend "local" {}
}

terraform {
  required_version = ">= 0.12"
}

provider "aws" {
  region  = "us-west-2"
  version = "~> 2.64"
}

provider "external" {
  version = "~> 1.2"
}

resource "aws_ecs_cluster" "test" {
  name = "test-cluster1"
}

data "external" "noop" {
  program = ["python", "-c", "print('{}')"]
  depends_on = [aws_ecs_cluster.test]
}
```

### Debug Output

Can be provided if absolutely necessary; its a lot to sanitize.

### Expected Behavior

Terraform should run the external data source after the dependent resource without prompting.  Here's an example showing the expected behavior with `depends_on` commented out:
```
data.external.noop: Refreshing state...
aws_ecs_cluster.test: Refreshing state... [id=arn:aws:ecs:us-west-2::cluster/test-cluster1]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Actual Behavior
Terraform prompts every time:
```
aws_ecs_cluster.test: Refreshing state... [id=arn:aws:ecs:us-west-2::cluster/test-cluster1]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 <= read (data resources)

Terraform will perform the following actions:

  # data.external.noop will be read during apply
  # (config refers to values not yet known)
 <= data "external" "noop"  {
      + id      = (known after apply)
      + program = [
          + "python",
          + "-c",
          + "print('{}')",
        ]
      + result  = (known after apply)
    }

Plan: 0 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

### Steps to Reproduce
1. Run `terraform apply` on the above sample
1. Run `terraform apply` again and note the confirmation prompt
1. Comment out the `depends_on` and run `terraform apply` again and note that the data source runs without prompting.

**Comment by apparentlymart** [comment]
Hi @elias314!

What you've described here is an intended behavior in Terraform prior to Terraform 0.13, which applies to all data resources. `depends_on` causes the read to always be deferred until the apply step because that's a conservative way to make sure that the read always happens after any action on the `aws_ecs_cluster.test` resource.

The forthcoming Terraform 0.13 includes an improvement to this behavior that came as a side-effect of the refactoring that was needed to support `count`, `for_each` and `depends_on` in `module` blocks: Terraform is now able to detect during the plan phase whether there is a planned change for any of the data resource's `depends_on` entries and defer to the apply phase _only if so_. That should create the behavior you were expecting in the situation you described, because your plan includes no action against `aws_ecs_cluster.test`.

There'll be an initial beta release of Terraform 0.13.0 coming out shortly, so you'll be able to give this a try and verify that it's now working as expected. Because this is a Terraform Core issue rather than an external provider issue, if you do find anything strange when you try this under a 0.13.0 beta please feel free to open an issue about it in [the Terraform Core repository](https://github.com/hashicorp/terraform).

(`external` provider maintainers: I believe there is nothing that could be changed _in this provider_ to alter the behavior described in this issue, because the described behavior is standard behavior for data resources in general, so I'd recommend closing this.)

**Comment by elias314** [comment]
I appreciate the detailed reply @apparentlymart .  I'll keep an eye out for 0.13.  Interestingly, I was able to work around the issue by creating an implicit dependency instead:

```
data "external" "noop" {
  program = ["python", "-c", "print('{}')"]
  query = {
    foo = aws_ecs_cluster.test.id
  }
}
```
Thanks again!

**Comment by apparentlymart** [comment]
Hi @elias314,

Indeed, implicit dependencies did not have this behavior even in prior versions of Terraform because Terraform was able to use the value itself to determine whether the operation would need to wait until apply time. (Specifically, Terraform defers a data resource read to apply time if any of its arguments are marked as `(known after apply)` due to being derived from an attribute of a resource has some changes pending.
