### ISSUE TITLE
Read when there are no changes

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform-provider-external#45]
### Terraform Version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/external v1.2.0

### Affected Resource(s)
- data "external"

### Expected Behavior
No changes == no confirmation and no data source info

### Actual Behavior
```hcl
  # module.some_module.data.external.some will be read during apply
  # (config refers to values not yet known)
 <= data "external" "some"  {
      + id          = "-"
      + program     = [
          + "python3",
          + "some.py",
        ]
      + query       = {
          + "output_secret_arn" = "arn:aws..."
        }
      + result      = {
          + "output" = "null"
        }
    }

Plan: 0 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "some"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
```
### Steps to Reproduce

1. Create external data source with some script output inside of a module
2. (NOT SURE IF REQUIRED) Add depends_on block that will wait for some resource (for example null_resource)
3. (NOT SURE IF REQUIRED) Add module output from external data source
4. `terraform apply` to save everything to the state
5. Rename the module folder and rename the actual import via `module "some_new" { src = new path }`
6. `terraform init`
7. `terraform apply` to save everything to the state
8. `terraform apply` again and hopefully you will encounter same problem.

### References
Similar issue to https://github.com/hashicorp/terraform/issues/25511

**Comment by mgzenitech** [comment]
By comparing the state file I've found that all of these data sources have "null" output:
```json
            "result": {
              "output": "null"
            },
```

this surely is wrong as they should have outputs saved as other data sources right?

**Comment by mgzenitech** [comment]
PS: What is interesting is that not every single external data source is triggered only some. For example all of these are triggered:
```json
    {
      "module": "SOMEMODULE",
      "mode": "data",
      "type": "external",
      "name": "get_output",
      "provider": "provider[\"registry.terraform.io/hashicorp/external\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "-",
            "program": [
              "python3",
              "get_output.py"
            ],
            "query": {
              "aws_region": "eu-west-2",
              "credentials_file": "HIDDEN",
              "output_secret_arn": "HIDDEN"
            },
            "result": {
              "output": "null"
            },
            "working_dir": "../modules/utils/local_script/script"
          }
        }
      ]
    },
```
yet these are not triggered:
```json
    {
      "module": "SOMEOTHERMODULE",
      "mode": "data",
      "type": "external",
      "name": "get_output",
      "provider": "provider[\"registry.terraform.io/hashicorp/external\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "-",
            "program": [
              "python3",
              "get_output.py"
            ],
            "query": {
              "aws_region": "eu-west-2",
              "credentials_file": "HIDDEN",
              "output_secret_arn": "HIDDEN"
            },
            "result": {
              "output": "\"not null string\""
            },
            "working_dir": "../modules/utils/local_script/script"
          }
        }
      ]
    },
```

**Comment by mgzenitech** [comment]
The only difference is that ones that are triggered is basically my script returning string **"null"**

**Comment by mgzenitech** [comment]
I've tried setting empty string still a no go:
```json
      result      = {
          "output" = "\"\""
      }
```
still triggers empty updates on same data sources

**Comment by mgzenitech** [comment]
Right looks like I've found where the issue lies...

```hcl
data "external" "get_output" {
  working_dir = local.triggers.working_dir
  program = [
    local.is_unix ? "python3" : "python",
    "get_output.py"
  ]
  query = length(null_resource.script_create) > 0 ? {
    aws_region = null_resource.script_create[0].triggers.aws_region
    credentials_file = null_resource.script_create[0].triggers.credentials_file
    output_secret_arn = null_resource.script_create[0].triggers.output_secret_arn
  } : {
    aws_region = data.aws_region.current.name
    credentials_file = local.relative_path_credentials_file
    output_secret_arn = aws_secretsmanager_secret.script_output.arn
  }
  depends_on = [
    null_resource.script_create
  ]
}
```

After I've renamed the module `length(null_resource.script_create) > 0` started to always trigger the update. So if I hardcode it to for example `query = true ? {` it will not show updates anymore. Something happens with resource **count** and state **after we rename the module**...

**Comment by bflad** [comment]
Hi @mgzenitech 👋  Thank you for raising this and apologies for the delayed response.

When working with data sources, including explicit dependencies via `depends_on`, it may force Terraform to refresh the data source every plan since values may not be known. Some of this is detailed in the [Terraform configuration language documentation](https://www.terraform.io/docs/language/data-sources/index.html#data-resource-dependencies).

It is probably also worth mentioning that Terraform CLI version 0.13 had some unique graph handling for data sources as compared to other Terraform CLI versions. Upgrading to 0.14 and later may introduce more expected behaviors.

In any case however, these Terraform configuration/CLI behaviors cannot be influenced by this provider or data source, so as such I'm going to close out this issue in this repository. If you believe there is undesirable behavior with Terraform CLI's configuration or data source behaviors on recent versions, please see the [Terraform CLI issues](https://github.com/hashicorp/terraform/issues) and potentially open one there. If you have further configuration or troubleshooting questions, please also check out [HashiCorp Discuss](https://discuss.hashicorp.com/) where there are far more folks watching these types of topics and able to answer. Thanks!
