### ISSUE TITLE
Allow HCL output output for resource "external" or introduce resource "external_hcl"

### ISSUE THREAD

**Issue by Nowaker** [hashicorp/terraform-provider-external#6]
It would be cool to do one of these two:

1. Allow `resource "external"` to return HCL syntax - not just JSON, or
2. Introduce `resource "external_hcl"` that allows HCL output

Currently, HCL output for `resource "external"` won't be accepted:

```
Error refreshing state: 1 error(s) occurred:

* data.external.users: 1 error(s) occurred:

* data.external.users: data.external.users: command "ruby" produced invalid JSON: invalid character '/' looking for beginning of value
```

**Comment by bflad** [comment]
Hi @Nowaker 👋  Thank you so much for filing this feature request.

HCL is a schema-based meta-language and typically only useful when combined with application-specific handling (such as Terraform's configuration language constructs), so therefore it is difficult to support a generic use case for HCL inputs and outputs in this provider without also thinking about how to inject application-specific abilities. There is also a slippery slope of which other encodings the data source could further support natively (e.g. YAML, TOML, etc.).

The provider is specifically designed around JSON handling since it is a fairly ubiquitous industry standard for machine readable data and long term, it will likely remain that way. This is going to be documented as part of #80, if it is not clear elsewhere. Since this issue was filed, Terraform CLI also now natively supports JSON and YAML decoding/encoding functions, which is a pattern that can be expanded for the future depending on use cases. It will still be expected that programs for usage with this provider would use the JSON input/output interface though. In your scenario, it may be best to implement your own provider that performs HCL-based output parsing for your program or have a program that handles the JSON conversion automatically.

If you are interested in further reading about Terraform CLI potentially supporting the ability to encode or decode Terraform's constructs in HCL or seeing a much more comprehensive explanation to this problem, I would recommend checking out https://github.com/hashicorp/terraform/issues/25584. That type of feature would likely be a more canonical solution to this problem, rather than a targeted solution only affecting one data source in one provider. Thanks again for submitting this!
