### ISSUE TITLE
value passed through query contains dodgy code/characters

### ISSUE THREAD

**Issue by JoshiiSinfield** [hashicorp/terraform-provider-external#9]
I have an external data program to create a resource for which there is not a Terraform resource for yet, however I need to pad 0's in front of a single digit for formatting of a name automatically.

Therefore, I have tried using the Terraform "format" interpolation function to do this, then passing that value into the query parameter of the external data program however this causes the python to fail due to some sort of code evaluation not happening within the external data source.

I'm not sure if it's an issue with this provider or an issue with the interpolation function or the way a string interpolation is performed before being passed into this provider, so I'm happy to raise the issue in the terraform core if required.

### Terraform Version
```
$ terraform -v
Terraform v0.11.1
```

### Terraform Configuration Files

```hcl
variable "network_number_8" {
  default = "8"
}

data "external" "test" {
  program = ["python", "test.py"]

  query {
    test_good = "${var.network_number_8}"
    test_bad  = "${format("%03d",var.network_number_8)}"
  }
}
```

### Python code for external data source
```python
import json
import sys

args = json.load(sys.stdin)
json.dump(args, sys.stderr)
exit(1)

```

### Actual Behavior
```
$ terraform apply
data.external.test: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.external.test: 1 error(s) occurred:

* data.external.test: data.external.test: failed to execute "python": {"test_bad": "%!d(string=008)", "test_good": "8"}
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by kmoe** [comment]
Thanks for your patience. The world has changed somewhat under our feet in the last four years, but one change I hope we can welcome is the resolution of this issue. 

With today's Terraform v1.0.1 and terraform-provider-external v2.1.0, this is the result I get with your config (having added the missing "=" between "query" and "{" in accordance with the 0.12 [Attributes vs Blocks](https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks) change):

```
$ terraform apply 
╷
│ Error: failed to execute "python": {"test_bad": "008", "test_good": "8"}
│ 
│   with data.external.test,
│   on main.tf line 5, in data "external" "test":
│    5: data "external" "test" {
│ 
```

This is expected, because test.py exits with a non-zero exit code. If we change line 6 of test.py to `exit(0)` instead, we get:

```
$ terraform apply 
╷
│ Error: command "python" produced invalid JSON: unexpected end of JSON input
│ 
│   with data.external.test,
│   on main.tf line 5, in data "external" "test":
│    5: data "external" "test" {
│ 
╵
```

This is also expected, because the python script does not output valid JSON (the output is "8"). 

Please see the [External Program Protocol](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source#external-program-protocol) section of the external provider documentation for more information on how to make test.py interoperable with this data source, and please reopen this issue if you believe there is a bug in the provider.
